PUT http://localhost:3001/user/67c49226116ad7684cb13b92
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzQ5MjI2MTE2YWQ3Njg0Y2IxM2I5MiIsInVzZXJuYW1lIjoicm9vdF91c2VyIiwiZW1haWwiOiJyb290QGdtYWlsLmNvbSIsImlhdCI6MTc0MTIwMzI0NywiZXhwIjoxNzQxMjIxMjQ3fQ.3Nf5KL1mG1mmGElDhPW3F8m1e2FnoPL0_GFkrAEj4_E

{
  "username": "root_user",
  "email": "root@gmail.com",
  "picture": null,
  "friends": ["67c493456ad88f62eff42f5f"]
}

####
# malformatted friend id
PUT http://localhost:3001/user/67c4572228693c82d97ceb3d
Content-Type: application/json
Authorization: Bearer 

{
  "username": "khadj999",
  "email": "khadj999@gmail.com",
  "picture": null,
  "friends": ["67c369accbd688a40120d859", "67c369accbd688a40120d85"]
}

####
# cannot befriend yourself
PUT http://localhost:3001/user/67c4572228693c82d97ceb3d
Content-Type: application/json
Authorization: Bearer 

{
  "username": "khadj999",
  "email": "khadj999@gmail.com",
  "picture": null,
  "friends": ["67c369accbd688a40120d859", "67c4572228693c82d97ceb3d"]
}